//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulUdalIzmenDobav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID_Account { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int id_AccountType { get; set; }
        public string Image { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
