//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulUdalIzmenDobav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int ID_Dogovor { get; set; }
        public Nullable<int> id_Tip_dogovora { get; set; }
        public Nullable<System.DateTime> Data_zaklyucheniya { get; set; }
        public Nullable<long> Summa_sdelki { get; set; }
        public Nullable<int> id_Ob_ekta { get; set; }
        public Nullable<int> id_Statusa_dogovora { get; set; }
        public Nullable<int> id_Sotrudnika { get; set; }
        public Nullable<int> id_Vladel_ca { get; set; }
    
        public virtual Obekt_nedvizhimosti Obekt_nedvizhimosti { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Status_dogovora Status_dogovora { get; set; }
        public virtual Tip_dogovora Tip_dogovora { get; set; }
        public virtual Vladelec Vladelec { get; set; }
    }
}
