//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulUdalIzmenDobav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obekt_nedvizhimosti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obekt_nedvizhimosti()
        {
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int ID_Ob_ekt_nedvizhimosti { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Ploshchad { get; set; }
        public Nullable<int> Kolichestvo_komnat { get; set; }
        public Nullable<System.DateTime> Data_dobavleniya { get; set; }
        public Nullable<System.DateTime> Data_izmeneniya { get; set; }
        public Nullable<long> Stoimost { get; set; }
        public Nullable<int> id_Status_ob_ekta_nedvizhimosti { get; set; }
        public Nullable<int> id_Tip_nedvizhimosti { get; set; }
        public string Izobrazhenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
        public virtual Status_ob_ekta_nedvizhimosti Status_ob_ekta_nedvizhimosti { get; set; }
        public virtual Tip_nedvizhimosti Tip_nedvizhimosti { get; set; }
    }
}
