//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulUdalIzmenDobav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_ob_ekta_nedvizhimosti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status_ob_ekta_nedvizhimosti()
        {
            this.Obekt_nedvizhimosti = new HashSet<Obekt_nedvizhimosti>();
        }
    
        public int ID_Status_ob_ekta_nedvizhimosti { get; set; }
        public string Naimenovanie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obekt_nedvizhimosti> Obekt_nedvizhimosti { get; set; }
    }
}
