//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulUdalIzmenDobav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vladelec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vladelec()
        {
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int ID_Vladelec { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<System.DateTime> Data_rozhdeniya { get; set; }
        public string Elektronnaya_pochta { get; set; }
        public Nullable<long> Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Seriya_pasporta { get; set; }
        public Nullable<int> Nomer_pasporta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
    }
}
